title: Kim Guynn Realtor®
tagline: Expert in Buying and Selling homes
email: kimaguynn@gmail.com
description: Expert in Buying and Selling homes in Bay county.
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://kimguynn.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
kim-blog:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman

# social
author: "Kim Guynn"

twitter:
  username: kimguynn
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  #app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
